### ISSUE TITLE
Open file handles prevent containers from being removed

### ISSUE THREAD

**Issue by chibacityblues** [monitoringartist/zabbix-agent-xxl#28]
I'm using dockbix-agent-xxl-limited on one of our CI systems for evaluation. While working nicely, I encountered an issue when containers are removed (either by hand or by CI):

```
Removing my_app_staging_db ... error

ERROR: for my_app_staging_db  Unable to remove filesystem for 4170b684a2bd193d6e5f73717d20fd4266afcf04ba0c5737d6649bc1e3365107: remove /var/lib/docker/containers/4170b684a2bd193d6e5f73717d20fd4266afcf04ba0c5737d6649bc1e3365107/shm: device or resource busy
```
Digging deeper revealed dockbix-agent-xxl as the blocking process:

```
$ grep -l 4170b684a2 /proc/*/mountinfo
/proc/14571/mountinfo
$ ps -f 14571
UID        PID  PPID  C STIME TTY      STAT   TIME CMD
root     14571 14556  0 Mai02 ?        Ssl    0:00 /dockbix-agent-xxl
```
After stopping the agent-container, removing other containers works again.

Is there something I can do about this?

**Comment by jangaraj** [comment]
Thx for report. You can't improve it. Let me see what I can do in the code.

**Comment by samkrew** [comment]
Hello! You can't fix it. cAdvisor have got same issue with AUFS.
Everyone should use OverlayFS to avoid this issue.

**Comment by jangaraj** [comment]
Yes, I follow https://github.com/google/cadvisor/issues/771. It looks like a problem of used Docker golang library. monitoringartist/dockbix-agent-xxl-limited uses that library to collect stats data. Unfortunately used library doesn't support **disconnect** function. In the theory paid image monitoringartist/dockbix-agent-xxl doesn't have this issue, because it doesn't initialize Docker golang library.

OverlayFS can be a workaround, but you may find another type of issues related to overlayfs https://github.com/monitoringartist/dockbix-agent-xxl/issues/16

**Comment by jangaraj** [comment]
I've added signal forwarding (3.4-3+ version), so any SIGTERM signal(s) from the docker daemon will also be forwarded to the zabbix_agentd. It may help with this issue.
